# path to folder with gml files for threshold graph calculation
input_graphs: simulated_complexes/small_test_true/

input_graphs_nx: simulated_complexes/small_test_true_nx/

weight_threshold_graph: 50

min_thresh: [0.70]

subsample_n: [100, 500]

seed: 42

thresh: [0.5, 0.6, 0.7, 0.8, 0.9]

false_negative_rate: [0.01]#, 0.001, 0.0001]

